# Generated by Django 2.1.7 on 2019-04-04 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('AdminId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=8)),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('CommentId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Comment', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('CourseName', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('Introduction', models.CharField(max_length=9000)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('CourseId', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('Username', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Login1',
            fields=[
                ('Username', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=8)),
                ('Name', models.CharField(max_length=20)),
                ('EmailId', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('SubjectID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('SubjectName', models.CharField(max_length=40)),
                ('Url', models.CharField(default='', max_length=25)),
                ('CourseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyLearn.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Subjectinfo',
            fields=[
                ('Subjectname', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Subjectinfo', models.CharField(max_length=8000)),
                ('Videourl', models.CharField(max_length=40)),
                ('Docurl', models.CharField(max_length=40)),
                ('ImageUrl', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='SubjectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyLearn.Subject'),
        ),
        migrations.AddField(
            model_name='comments',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyLearn.Student'),
        ),
    ]
