# Generated by Django 2.1.7 on 2019-04-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyLearn', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCourse',
            fields=[
                ('SubjectId', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Subjectname', models.CharField(max_length=12)),
                ('Comment', models.CharField(max_length=40)),
            ],
        ),
    ]
