# Generated by Django 2.1.7 on 2019-04-05 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyLearn', '0003_reviewcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subjectname', models.CharField(max_length=12)),
                ('Comment', models.CharField(max_length=40)),
                ('SubjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyLearn.Student')),
            ],
        ),
        migrations.RenameModel(
            old_name='ReviewCourse',
            new_name='ReviewCourse1',
        ),
    ]
