# Generated by Django 2.1.7 on 2019-04-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyLearn', '0006_auto_20190405_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcourses',
            name='StudentID',
            field=models.CharField(default='', max_length=12),
        ),
    ]
